server:
  port: 8000
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/worker
spring:
  application:
    name: workerServer

# RocketMQ 相关配置
rocketmq:
  # 指定 nameServer
  name-server: ${ROCKETMQ_NAMESERVER:192.168.31.200:9876;192.168.31.200:9877;192.168.31.200:9878}
  # Producer 生产者
  producer:
    # 指定发送者组名
    group: WORKER_PRODUCER_GROUP
    # 发送消息超时时间，单位：毫秒，默认为 3000
    send-message-timeout: 10000
    # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
    compress-message-body-threshold: 4096
    # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
    max-message-size: 104857600
    # 同步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-failed: 2
    # 异步发送消息时，失败重试次数。默认为 2 次。
    retry-times-when-send-async-failed: 2
    # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
    retry-next-server: true